version: "3.3"

services:
  flasks:
    build: flasks/.
    ports:
      - "${FLASK_PORT:-5001}:5000"
    expose:
      - "5000"
    depends_on:
      - db
    env_file:
      - ./flasks/mysql.env
      - ./flasks/${FLASK_ENV}
    restart: always
  db:
    image: docker.io/library/mariadb:10.9.2-jammy
    expose:
      - "3306"
    volumes:
      - "${MARIA_DB_VOLUME:-mariadb-test-data}:/var/lib/mysql"
      - "./mariadb/entry:/docker-entrypoint-initdb.d"
    env_file:
      - ./flasks/mysql.env
      - ./mariadb/mysql_root.env
    restart: always
volumes:
  mariadb-data:
  mariadb-test-data: